# fly.toml app configuration file generated for musiikinjakosovellus on 2024-02-04T23:33:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'musiikinjakosovellus'
primary_region = 'arn'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
